### ISSUE TITLE
Crashes on retry after network is restored

### ISSUE THREAD

**Issue by TedHopp** [googlecodelabs/android-paging#105]
When a new search is begun and there is no connectivity, the UI displays the "RETRY" button. If the button is clicked after connectivity is restored (with the same search string), the app crashes. Here's the stack trace:

```
2020-09-02 17:56:17.050 31924-31924/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 31924
    java.io.InvalidObjectException: Remote key and the prevKey should not be null
        at com.example.android.codelabs.paging.data.GithubRemoteMediator.load(GithubRemoteMediator.kt:56)
        at com.example.android.codelabs.paging.data.GithubRemoteMediator$load$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

It appears that calling `adapter.refresh()` in this situation leads to a call to the mediator's `load()` method with a `LoadType` of `PREPEND` rather than `REFRESH` even though it is, in theory, a new search being retried.

This happens when using recycler view version 1.2.0-alpha05, room version 2.3.0-alpha02, and paging version 3.0.0-alpha05.

**Comment by florina-muntenescu** [comment]
Fixed meanwhile
