### ISSUE TITLE
App crashes if first run without network

### ISSUE THREAD

**Issue by TedHopp** [googlecodelabs/android-paging#120]
In the final configuration (with RemoteMediator), If the app is run when the network is not available (e.g., device in airplane mode), then the app always crashes with:

```
2020-10-20 21:37:31.273 20431-20431/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 20431
    java.io.InvalidObjectException: Remote key and the prevKey should not be null
        at com.example.android.codelabs.paging.data.GithubRemoteMediator.load(GithubRemoteMediator.kt:38)
        at androidx.paging.RemoteMediatorAccessor.doLoad(RemoteMediatorAccessor.kt:96)
        at androidx.paging.RemoteMediatorAccessor$load$$inlined$withLock$lambda$1.invokeSuspend(RemoteMediatorAccessor.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:333)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:91)
        at kotlinx.coroutines.BuildersKt.async(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:84)
        at kotlinx.coroutines.BuildersKt.async$default(Unknown Source:1)
        at androidx.paging.RemoteMediatorAccessor.load$paging_common(RemoteMediatorAccessor.kt:64)
        at androidx.paging.PageFetcherSnapshot.doBoundaryCall(PageFetcherSnapshot.kt:551)
        at androidx.paging.PageFetcherSnapshot.doInitialLoad(PageFetcherSnapshot.kt:380)
        at androidx.paging.PageFetcherSnapshot$doInitialLoad$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

For some reason, even though there is no data in the data base, `load()` is called with a load type of `PREPEND`. If I doctor the logic to return `GITHUB_STARTING_PAGE_INDEX` instead of throwing an exception, then `load()` is also called with a load type of `APPEND`.

There seems to be no reason for the library to be calling the remote mediator to load data with these load types when data are not available and the `REFRESH` call returns zero objects.

**Comment by florina-muntenescu** [comment]
Code changed meanwhile so I can't reproduce this.
Please re-open if this still happens. 
Thanks!
