### ISSUE TITLE
paging some error

### ISSUE THREAD

**Issue by laibinzhi** [googlecodelabs/android-paging#76]
When I keep sliding the list, when the paging request network is triggered, the list automatically runs to the top

**Comment by laibinzhi** [comment]
2020-07-10 17:40:55.148 7211-7211/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 7211
    java.lang.UnsupportedOperationException: Unknown view
        at com.example.android.codelabs.paging.ui.ReposAdapter.getItemViewType(ReposAdapter.kt:42)
        at androidx.recyclerview.widget.NestedAdapterWrapper.getItemViewType(NestedAdapterWrapper.java:146)
        at androidx.recyclerview.widget.ConcatAdapterController.getItemViewType(ConcatAdapterController.java:318)
        at androidx.recyclerview.widget.ConcatAdapter.getItemViewType(ConcatAdapter.java:177)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6298)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6231)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6227)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4230)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3941)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1974)
        at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2013)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3477)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3466)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5229)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5029)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4597)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4563)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4703)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4571)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4760)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4597)
2020-07-10 17:40:55.149 7211-7211/com.example.android.codelabs.paging E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4563)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4571)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4544)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7262)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7231)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7192)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7368)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:249)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:212)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7336)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7391)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1101)
        at android.view.Choreographer.doCallbacks(Choreographer.java:896)
        at android.view.Choreographer.doFrame(Choreographer.java:821)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1087)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by siddhantkumar20** [comment]
this bug and crashing bug is cause by
`lifecycleScope.launch { @OptIn(ExperimentalPagingApi::class) adapter.dataRefreshFlow.collect { binding.list.scrollToPosition(0) } }`
I removed this code and everything seems to work fine, IDK BUT....
I guess dataRefreshFlow is getting called when data is appended or prepended , causing recyclerview to scroll to top, which causes recyclerview to throw exception in the second case when this happens.
I also tried to update to latest release of pagination and recyclerview libs but same thing,
For now this thing works well..

**Comment by florina-muntenescu** [comment]
Fixed meanwhile please force pull
