### ISSUE TITLE
InvalidObjectException: Remote key and the prevKey should not be null

### ISSUE THREAD

**Issue by doilio** [googlecodelabs/android-paging#93]
This error shows up the first time I run the completed codelab.

```
2020-07-26 16:25:41.483 29361-29361/com.example.android.codelabs.paging D/GithubRepository: New query: Android
2020-07-26 16:25:41.664 29361-29361/com.example.android.codelabs.paging D/GithubRemote: Current Page: 1 and LoadType = REFRESH
2020-07-26 16:26:25.761 29361-29361/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 29361
    java.io.InvalidObjectException: Remote key and the prevKey should not be null
        at com.example.android.codelabs.paging.data.GithubRemoteMediator.load(GithubRemoteMediator.kt:57)
        at androidx.paging.RemoteMediatorAccessor.doLoad(RemoteMediatorAccessor.kt:96)
        at androidx.paging.RemoteMediatorAccessor$doLoad$1.invokeSuspend(Unknown Source:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.ResumeOnCompletion.invoke(JobSupport.kt:1394)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

When I run again It works fine:
```
020-07-26 16:29:33.261 29558-29558/com.example.android.codelabs.paging D/GithubRepository: New query: Android
2020-07-26 16:29:33.471 29558-29558/com.example.android.codelabs.paging D/GithubRemote: Current Page: 1 and LoadType = REFRESH
2020-07-26 16:29:46.749 29558-29558/com.example.android.codelabs.paging D/GithubRemote: Current Page: 2 and LoadType = APPEND
2020-07-26 16:29:49.151 29558-29558/com.example.android.codelabs.paging D/GithubRemote: Current Page: 3 and LoadType = APPEND
2020-07-26 16:29:52.113 29558-29558/com.example.android.codelabs.paging D/GithubRemote: Current Page: 4 and LoadType = APPEND
```

If I uninstall and install it again. It shows me the same error

**Comment by victor-ka-1** [comment]
Probably this is because of return in fun load().  MediatorResult.Success(endOfPaginationReached) returns before coroutine will finish adding all data ( repoDatabase.reposDao().insertAll(repos) and repoDatabase.remoteKeysDao().insertAll(keys) ) to database. So first time it has state(i mean PagingState) with page 1(default), but no data, so this will cause return null RemoteKeys in getRemoteKeyForFirstItem() and then Exception.

**Comment by ruffCode** [comment]
Seems like a race condition. On initial start, the load function is called with type REFRESH, the keys and repos are written (or are being written) to the db, load is called immediately with PREPEND and the keys are null.

My solution was to wrap the call to getRemoteKeyForFirstItem in a flow, as such:

`val remoteKeys: RemoteKeys? = flowOf(getRemoteKeyForFirstItem(state)).flowOn(Dispatchers.IO).single()`

I'm sure that this is not the ideal solution, but it's the best I could come up with.

I'll submit a PR

**Comment by Petterpx** [comment]
> 好像是比赛条件。在初始启动时，使用REFRESH类型调用load函数，将键和存储库写入（或正在写入）db，使用PREPEND立即调用load，并且键为空。
> 
> 我的解决方案是将对getRemoteKeyForFirstItem的调用包装在一个流中，如下所示：
> 
> `val remoteKeys: RemoteKeys? = flowOf(getRemoteKeyForFirstItem(state)).flowOn(Dispatchers.IO).single()`
> 
> 我确定这不是理想的解决方案，但这是我能想到的最好的解决方案。
> 
> 我要提交公关

I used your method and still have this problem.
Remote key should not be null for APPEND

**Comment by CelikAbdullah** [comment]
I have the same problem. Is there any official solution provided to that problem ?

**Comment by iamarjun** [comment]
@CelikAbdullah try this PR: https://github.com/googlecodelabs/android-paging/pull/112 worked like a wonder for me

**Comment by android-taoge** [comment]
does anyone solve this problem?  it's a bad experience for me .

**Comment by dlam** [comment]
Latest PR pending merge should fix this https://github.com/googlecodelabs/android-paging/pull/152
